services:
  - type: web
    name: ladies-sauna-api
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npx prisma migrate deploy && npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ladies-sauna-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://ladies-sauna.vercel.app

databases:
  - name: ladies-sauna-db
    databaseName: ladies_sauna_db
    user: ladies_sauna_user